sonar.projectKey=mingbugsman_discord-bot-devops-pipeline
sonar.organization=ming-bugs-man
sonar.host.url=https://sonarcloud.io
sonar.sources=.
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml